# Generated by Django 5.1.1 on 2025-02-18 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=50)),
                ('menu', models.TextField()),
                ('timing', models.TimeField()),
                ('last_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('left_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hosteller',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('room_number', models.CharField(blank=True, max_length=15)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('is_inside', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('fine', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('email', models.EmailField(default='172003rash@gmail.com', max_length=254)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('semester', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('father_image', models.ImageField(blank=True, null=True, upload_to='parent_images/')),
                ('mother_image', models.ImageField(blank=True, null=True, upload_to='parent_images/')),
                ('parent_address', models.CharField(blank=True, max_length=255)),
                ('parent_number', models.CharField(blank=True, max_length=15)),
                ('lg_name', models.CharField(blank=True, max_length=255)),
                ('relation', models.CharField(blank=True, max_length=255)),
                ('lg_number', models.CharField(blank=True, max_length=255)),
                ('lg_address', models.CharField(blank=True, max_length=255)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hosteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hosteller')),
            ],
        ),
        migrations.CreateModel(
            name='EntryExitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('hosteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hosteller')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hosteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hosteller')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10)),
                ('hosteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hosteller')),
            ],
        ),
        migrations.CreateModel(
            name='LeavePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('hosteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hosteller')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('hosteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hosteller')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(max_length=50)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hosteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hosteller')),
            ],
        ),
    ]
