# Generated by Django 5.1.6 on 2025-02-21 03:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_alter_hosteller_qr_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique_for_date='hosteller'),
        ),
    ]
