# Generated by Django 5.1.6 on 2025-02-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(choices=[('light_fan', 'Light/Fan Issue'), ('wifi', 'WiFi Issue'), ('water', 'Water Issue'), ('cleaning', 'Cleaning Issue'), ('bathroom', 'Bathroom Cleanliness Issue')], default='light_fan', max_length=20),
        ),
        migrations.AddField(
            model_name='leavepass',
            name='leave_id',
            field=models.CharField(choices=[('outing', 'Outing'), ('work', 'Work'), ('college_holiday', 'College Holiday'), ('family_function', 'Family Function')], default='work', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='leavepass',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
