# Generated by Django 5.1.6 on 2025-02-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_complaint_complaint_id_leavepass_leave_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_id',
            new_name='complaint_type',
        ),
        migrations.RenameField(
            model_name='leavepass',
            old_name='leave_id',
            new_name='leave_type',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='subject',
        ),
    ]
