# Generated by Django 5.1.6 on 2025-02-22 09:09

import django.utils.timezone
import hostel.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_rename_complaint_id_complaint_complaint_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=hostel.storages.StaticFileStorage(), upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique_for_date='date'),
        ),
    ]
