# Generated by Django 5.1.6 on 2025-02-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_alter_attendance_date_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='check_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
